### ISSUE TITLE
New Event Card

### ISSUE THREAD

**Issue by virajchandra51** [TCP-Tech/CodeUtsava7.0#36]
- Design a new Event Card.
- This card will have picture.
- Map the card component to appropriate event data set, and use the appropriate objects keys accordingly, such as dates, link etc.
- Delete the previous Event Card and replace it with yours.
- Submit SS/Video of the component in working condition.
- Use good naming convention for CSS classes.
- Avoid usage of any external library.
- The card should symbolise our theme of Halloween. Idea - Stick spiderwebs in top corners of a pumpkin near the bottom , maybe a picture of a small graveyard tablet. Use the smallest size assets available for this, preferred SVG.

**Comment by Adarshkumar03** [comment]
I would like to work on this issue

**Comment by Adarshkumar03** [comment]
I would like to work on this issue

**Comment by virajchandra51** [comment]
We need a register now button too.

**Comment by Adarshkumar03** [comment]
Okay
